### PR TITLE
drop py2 support, use pyrlp 1.0, switch travis to py3

### LINKED ISSUE #872: pyethereum depends on some python3-only packages
Here is the list of transitive dependencies pyethereum depends on:

```
asn1crypto==0.24.0
cffi==1.11.5
coincurve==7.1.0
cytoolz==0.9.0.1
eth-hash==0.1.2
eth-utils==1.0.3
ethereum==2.3.1
future==0.16.0
pbkdf2==1.3
py-ecc==1.4.2
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
pysha3==1.0.2
PyYAML==3.12
repoze.lru==0.7
rlp==1.0.1
scrypt==0.8.6
toolz==0.9.0
```

This is the output of `pip3 freeze` in:

```
python3 -m venv .
source bin/activate
pip3 install ethereum
pip3 freeze
```

The packages `rlp` and `eth-utils`, at least, don't actually advertise support for python2. according to PyPI `rlp` dropped support moving from 0.6.0 to 1.0.0, and `eth-utils` dropped support for it when moving from 0.8.1 to 1.0.0. I personally don't use python2 but this does cause the CI to fail, because of this line in `eth-utils` which uses the python3-only `raise...from` syntax.

https://github.com/ethereum/eth-utils/blob/master/eth_utils/applicators.py#L77

(note that `eth-utils` is a transitive dependency through `rlp`, and not a direct dependency, but we still import `eth-utils` in this codebase, which should probably be fixed in the future)

Personally, I would get rid of python2 support, but the last time this was discussed (#442) it seems some people are still using pyethereum with python2. If this is still the case I propose:

1. Dropping support for python2 in master
1. Cutting a new 2.X.X branch with python2 support which pins `rlp` and `eth-utils` to `0.6.0` and `0.8.1`, but not actively porting new features to it, as a bridge to help teams still using python2
1. Cutting a new 3.0.0 branch which drops python2 support, and making new releases on 3.X.X

cc @pipermerriam since I think he mantains `rlp` and `eth-utils`, and he opened #442

### PR DESCRIPTION
**Pull request by ldct**
fixes #872

### CODE REVIEW

**Comment by volzkzg** [comment]
Cool, can use pyrlp 1.0 finally.

**Comment by ldct** [comment]
@joeykrug can you retry the build on master? currently failed with `Connection to files.pythonhosted.org timed out`

**Comment by hrishikeshio** [comment]
I am getting this issue https://github.com/ethereum/pyethereum/issues/876

**Comment by joeykrug** [comment]
Should be fixed now

**Pull request merged**
