### PR TITLE
fixes for Solidity 0.1.2 changes

### PR DESCRIPTION
**Pull request by ethers**
this issue was observed, debugged, fixed, and tested by running truffle and eth-testrpc

### CODE REVIEW

**Comment by ethers** [comment]
solidity tests pass:

py.test ethereum/tests/test_solidity.py 
============================= test session starts ==============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
plugins: timeout, capturelog, mock, xdist
collected 7 items 

ethereum/tests/test_solidity.py .......

=========================== 7 passed in 6.45 seconds ===========================

**Comment by heikoheiko** [comment]
thank you. can you add a version (>= x.y) check?

**Comment by heikoheiko** [comment]
merged, still it would be nice to check the version and report a structured error.

**Comment by ethers** [comment]
thanks I will check version next time I edit file, though I'm not sure how the test framework works with different solidity versions.  i can also open a issue to track checking the solc version.

**Pull request merged**
