### PR TITLE
fix hash value encoding in abi

### PR DESCRIPTION
**Pull request by janx**
fixed hash and bytes encoding and decoding.

### CODE REVIEW

**Comment by heikoheiko** [comment]
Hi janx, thank you very much for the PRs. But can you please create tests for them?
https://github.com/ethereum/pyethereum/blob/develop/ethereum/tests/test_abi.py

**Comment by janx** [comment]
@heikoheiko added.

btw. in ABI [wiki](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) the real/ureal type is named fixed/ufixed, is wiki obsolete?

**Comment by konradkonrad** [comment]
Could you please rebase on latest develop?

**Comment by janx** [comment]
close, merge into another PR.

**Pull request closed without merging**
