### PR TITLE
Piper/refactor guardain to more user friendly cli

### PR DESCRIPTION
**Pull request by pipermerriam**
Work in Progress for easier CLI interface to run guardian.

### CODE REVIEW

**Comment by pipermerriam** [comment]
@janx for your reviewing pleasure.  This is the next step I've been working on for running the guardian node.  It adds `click` which is a nice library I like for building command line tooling.

I'm going to spend some time tomorrow writing up some documentation on how to use it.

Things that still need to be done:

- cleanup commit history
- improve the stuff that's logged to stdout.  Currently it's a ton of junk.
- documentation
- make the `bet` objects serializable so that the node doesn't have to fully resync them when it resumes.

**Comment by janx** [comment]
@pipermerriam why `LDBase` use `leveldb.LevelDB` directly instead of `db.LevelDB`?

I managed to start 3 nodes by:

1. cli.py --data-dir {guard1, guard2, guard3} init
2. cp guard1/genesis.json {guard2,guard3}/
3. create config.json in {guard2, guard3}, set port and bootstrap_nodes
4. cli.py --data-dir guard1 run
5. sleep X seconds, run guard2 and guard3

however the other 2 nodes failed to join the guardian set , I guess I did something wrong. I'll have another test later.

**Comment by janx** [comment]
@pipermerriam why `LDBase` use `leveldb.LevelDB` directly instead of `db.LevelDB`?

I managed to start 3 nodes by:

1. cli.py --data-dir {guard1, guard2, guard3} init
2. cp guard1/genesis.json {guard2,guard3}/
3. create config.json in {guard2, guard3}, set port and bootstrap_nodes
4. cli.py --data-dir guard1 run
5. sleep X seconds, run guard2 and guard3

however the other 2 nodes failed to join the guardian set , I guess I did something wrong. I'll have another test later.

**Comment by pipermerriam** [comment]
@janx the piece that is missing is specifying the appropriate bootstrap nodes for the additional clients.

When the initial client starts up it will log it's `enode://...` address.  That needs to be placed in a config file for the additional clients.

```javascript
// config.json
{
    "port": 29871,
    "bootstrap_nodes": ["enode://9e0bf250f9e69c7c295064ec9c4d8aa43815bbd931737dacebc63eca2ecd7284c242e510bde3495b845b9d50434bbf78ca4b39120e1242edb3fca159bbb7372c@0.0.0.0:29870"]
}
```

Then you need to run with `--config path/to/config.json`

**Comment by pipermerriam** [comment]
Also, I've updated this PR with a new `ethereum/guardian/README.md` file that gives some basic instruction on how to use this.

**Comment by janx** [comment]
I did specify those boot nodes and nodes were connected, I guess I did something else wrong.

Now I tested with 3 nodes by following `ethereum/guardian/README.md` everything works well :coffee:

**Pull request merged**
